version: '3.1'
services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - '6556:3306'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_ROOT_PASSWORD: senha
    volumes:
      - ~/mysql_data:/var/lib/mysql
  wordpress:
    image: wordpress
    restart: always
    ports:
      - '8084:80'
    expose:
      -  '80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: senha
      WORDPRESS_DB_NAME: mysql_db
    volumes:
      - ~/site:/var/www/html
  adminer:
    image: adminer
    restart: always
    ports:
      - '8085:8080'
    expose:
      - '8080'